### ISSUE TITLE
Dribbble Todo

### ISSUE THREAD

**Issue by danielhickman** [xorprojects/Material-Web#1]
- [ ] Border Radius 2px for Waves on Cards
- [ ] Material Card Padding
- [ ] Side Nav Finish
- [ ] Active Nav Menu Links
- [ ] Profile Tabs
- [ ] Shot Details Styling
- [ ] Suggestions for Search
- [ ] FAB to Overlaying Function (not link)
- [ ] Animate Sidenav Dimmer (currently broken)
