### ISSUE TITLE
Side Nav Todo

### ISSUE THREAD

**Issue by danielhickman** [xorprojects/Material-Web#2]
- [ ] Active on children and subOnly
- [ ] Fix subOnly trigger 
- [ ] Active manual (by JS)
- [ ] Active by anchor href with a toggle in the config object
